package org.iqvis.nvolv3.utils;

public interface ISystemConstant {

	String SINCH_SIGNUP_API_URL = "SINCH_SIGNUP_API_URL";

	String APP_CONFIG_OAUTH_TWITTER_CALLBACK = "app.config.oauth.twitter.callback";

	String APP_CONFIG_OAUTH_TWITTER_API_SECRET = "app.config.oauth.twitter.apisecret";

	String APP_CONFIG_OAUTH_TWITTER_API_KEY = "app.config.oauth.twitter.apikey";

	String APP_CONFIG_OAUTH_FACEBOOK_CALLBACK = "app.config.oauth.facebook.callback";

	String APP_CONFIG_OAUTH_FACEBOOK_API_SECRET = "app.config.oauth.facebook.apisecret";

	String APP_CONFIG_OAUTH_FACEBOOK_API_KEY = "app.config.oauth.facebook.apikey";

	String APP_CONFIG_OAUTH_LINKEDIN_CALLBACK = "app.config.oauth.linkedin.callback";

	String APP_CONFIG_OAUTH_LINKEDIN_API_SECRET = "app.config.oauth.linkedin.apisecret";

	String APP_CONFIG_OAUTH_LINKEDIN_API_KEY = "app.config.oauth.linkedin.apikey";

	String ANALYTICS_GEO_LOCATION_AGGREGATION_REPORTING_URL = "ANALYTICS_GEO_LOCATION_AGGREGATION_REPORTING_URL";

	String ANALYTICS_CUSTOM_AGGREGATION_REPORTING_URL = "ANALYTICS_CUSTOM_AGGREGATION_REPORTING_URL";

	String ANALYTICS_PRIMARY_URL = "ANALYTICS_PRIMARY_URL";

	String ANALYTICS_CLIENT_ID = "ANALYTICS_CLIENT_ID";

	String EVENT_SEARCH_PREVIOUS_DAYS = "EVENT_SEARCH_PREVIOUS_DAYS";

	String APP_STARTUP_PREVIOUS_DAYS = "APP_STARTUP_PREVIOUS_DAYS";

	String DOWNLOAD_FILE_URL = "DOWNLOAD_FILE_URL";

	String TWITTER_FEED_FETCH_COUNT = "TWITTER_FEED_FETCH_COUNT";

	String ENVOIRNMENT_PRODUCTION = "PRODUCTION";

	String ENVOIRNMENT_DEVELOPMENT = "DEVELOPMENT";
	
	String SALES_EMAIL="SALES_EMAIL";
}
