package org.iqvis.nvolv3.utils;

public enum SystemConstantEnum {

	ENUM_SINCH_SIGNUP_API_URL,

	ENUM_APP_CONFIG_OAUTH_TWITTER_CALLBACK,

	ENUM_APP_CONFIG_OAUTH_TWITTER_API_SECRET,

	ENUM_APP_CONFIG_OAUTH_TWITTER_API_KEY,

	ENUM_APP_CONFIG_OAUTH_FACEBOOK_CALLBACK,

	ENUM_APP_CONFIG_OAUTH_FACEBOOK_API_SECRET, ENUM_APP_CONFIG_OAUTH_FACEBOOK_API_KEY,

	ENUM_APP_CONFIG_OAUTH_LINKEDIN_CALLBACK,

	ENUM_APP_CONFIG_OAUTH_LINKEDIN_API_SECRET,

	ENUM_APP_CONFIG_OAUTH_LINKEDIN_API_KEY,

	ENUM_ANALYTICS_GEO_LOCATION_AGGREGATION_REPORTING_URL,

	ENUM_ANALYTICS_CUSTOM_AGGREGATION_REPORTING_URL,

	ENUM_ANALYTICS_PRIMARY_URL,

	ENUM_ANALYTICS_CLIENT_ID,

	ENUM_EVENT_SEARCH_PREVIOUS_DAYS,

	ENUM_APP_STARTUP_PREVIOUS_DAYS,

	ENUM_DOWNLOAD_FILE_URL,

	ENUM_SALES_EMAIL,
	
	ENUM_TWITTER_FEED_FETCH_COUNT;
	

	@Override
	public String toString() {

		switch (this) {
		case ENUM_SINCH_SIGNUP_API_URL:

			return ISystemConstant.SINCH_SIGNUP_API_URL;
		case ENUM_APP_CONFIG_OAUTH_TWITTER_CALLBACK:

			return ISystemConstant.APP_CONFIG_OAUTH_TWITTER_CALLBACK;
		case ENUM_APP_CONFIG_OAUTH_TWITTER_API_SECRET:

			return ISystemConstant.APP_CONFIG_OAUTH_TWITTER_API_SECRET;
		case ENUM_APP_CONFIG_OAUTH_TWITTER_API_KEY:

			return ISystemConstant.APP_CONFIG_OAUTH_TWITTER_API_KEY;
		case ENUM_APP_CONFIG_OAUTH_FACEBOOK_CALLBACK:

			return ISystemConstant.APP_CONFIG_OAUTH_FACEBOOK_CALLBACK;
		case ENUM_APP_CONFIG_OAUTH_FACEBOOK_API_SECRET:

			return ISystemConstant.APP_CONFIG_OAUTH_FACEBOOK_API_SECRET;
		case ENUM_APP_CONFIG_OAUTH_FACEBOOK_API_KEY:

			return ISystemConstant.APP_CONFIG_OAUTH_FACEBOOK_API_KEY;
		case ENUM_APP_CONFIG_OAUTH_LINKEDIN_CALLBACK:

			return ISystemConstant.APP_CONFIG_OAUTH_LINKEDIN_CALLBACK;
		case ENUM_APP_CONFIG_OAUTH_LINKEDIN_API_SECRET:

			return ISystemConstant.APP_CONFIG_OAUTH_LINKEDIN_API_SECRET;
		case ENUM_APP_CONFIG_OAUTH_LINKEDIN_API_KEY:

			return ISystemConstant.APP_CONFIG_OAUTH_LINKEDIN_API_KEY;
		case ENUM_ANALYTICS_GEO_LOCATION_AGGREGATION_REPORTING_URL:

			return ISystemConstant.ANALYTICS_GEO_LOCATION_AGGREGATION_REPORTING_URL;
		case ENUM_ANALYTICS_CUSTOM_AGGREGATION_REPORTING_URL:

			return ISystemConstant.ANALYTICS_CUSTOM_AGGREGATION_REPORTING_URL;
		case ENUM_ANALYTICS_PRIMARY_URL:

			return ISystemConstant.ANALYTICS_PRIMARY_URL;
		case ENUM_ANALYTICS_CLIENT_ID:

			return ISystemConstant.ANALYTICS_CLIENT_ID;
		case ENUM_EVENT_SEARCH_PREVIOUS_DAYS:

			return ISystemConstant.EVENT_SEARCH_PREVIOUS_DAYS;
		case ENUM_APP_STARTUP_PREVIOUS_DAYS:

			return ISystemConstant.APP_STARTUP_PREVIOUS_DAYS;

		case ENUM_DOWNLOAD_FILE_URL:

			return ISystemConstant.DOWNLOAD_FILE_URL;

		case ENUM_TWITTER_FEED_FETCH_COUNT:

			return ISystemConstant.TWITTER_FEED_FETCH_COUNT;
			
		case  ENUM_SALES_EMAIL:
			
			return ISystemConstant.SALES_EMAIL;
		}

		return null;
	}

}
